### ISSUE TITLE
Error using decode_cntk2.sh with CUDA

### ISSUE THREAD

**Issue by mirco86** [Microsoft/CNTK#157]
Hi,
I'm trying to use CNTK with the Kaldi plug-in. I have trained a DNN of 6 hidden layers with CNTK (without any error using wsj5k data) and I'm trying now to use "decode_cntk2.sh" to decode the test signals using the following command:

steps/nnet_cntk/decode_cntk2.sh --nj 6 --cmd run.pl --acwt 0.1 --beam 18 --latbeam 10.0 /home/mravanelli/kaldi-trunk/egs/dirha_wsj5k/dirha_wsj5k_raw/exp/tri4/graph_tgpr_5k /home/mravanelli/kaldi-trunk/egs/dirha_wsj5k/dirha_wsj5k_raw/data-fmllr-tri4/sim_dev_onlyrev /home/mravanelli/kaldi-trunk/egs/dirha_wsj5k/dirha_wsj5k_raw/exp/exp_cntk1/decode_cntk_sim_dev_onlyrev_gpu4 cntk configFile=conf/cntk_config//CNTK2_write.config DeviceNumber=0 modelName=/home/mravanelli/kaldi-trunk/egs/dirha_wsj5k/dirha_wsj5k_raw/exp/exp_cntk1/cntk.dnn.29 labelDim=3288 featDim=40 action=write ExpDir=/home/mravanelli/kaldi-trunk/egs/dirha_wsj5k/dirha_wsj5k_raw/exp/exp_cntk1

If I set "DeviceNumber=-1" (cpu) it takes a lot of time, but the performance of the system seems reasonable.
if I set "DeviceNumber=0" (gpu) the accuracy drops dramatically. This is due to the fact that in the log file (e.g., /log/decode.4.log) there is the following error.

CUDA failure 2: out of memory ; GPU=0 ; hostname=oktem.fbk.eu ; expr=cudaMalloc((void**) &deviceBufferPtr, sizeof(AllocatedElemType) * numElements)
Closed Kaldi writer

I'm using a GTX680 with 2 GB of memory. With the original recipe of kaldi I had no problem in training and testing a comparable neural network.

Is there any parameter to change in the config file? How can I solve the problem?

Thank you!

Mirco

**Comment by dongyu888** [comment]
If this is only an out of memory problem, can you try putting

 

shareNodeValueMatrices=true

 

at the top of your config file and see whether this is sufficient to solve your problem?

**Comment by mirco86** [comment]
Hi, 
I have already tried it, but there is a very weird behaviour of the system.

The configuration file is this:

````
DeviceNumber=$DeviceNumber$`
command=$action$

precision=float

write=[
    action=write
    modelPath=$modelName$
    outputNodeNames=ScaledLogLikelihood

    # deviceId=-1 for CPU, >=0 for GPU devices 
    deviceId=$DeviceNumber$
    traceLevel=1
    useValidation=true

    printValues=true
      
    reader=[
      # reader to use
      readerType=Kaldi2Reader
      readMethod=blockRandomize
      frameMode=false
      miniBatchMode=Partial
      randomize=Auto
      verbosity=0   
      features=[
        dim=$featDim$
        scpFile=$inputCounts$
        rx=$inputFeats$
      ]

    ]
    writer=[
      # reader to use
      writerType=Kaldi2Reader
      readMethod=blockRandomize
      frameMode=false
      miniBatchMode=Partial
      randomize=Auto
      verbosity=0   
      ScaledLogLikelihood=[
        dim=$labelDim$
        Kaldicmd="ark:-"
        scpFile=$inputCounts$
      ]
    ]

]
```

While the command line is this:

`steps/nnet_cntk/decode_cntk2.sh --nj 6 --cmd run.pl --acwt 0.1 --beam 18 --latbeam 10.0 /home/mravanelli/kaldi-trunk/egs/dirha_wsj5k/dirha_wsj5k_raw/exp/tri4/graph_tgpr_5k /home/mravanelli/kaldi-trunk/egs/dirha_wsj5k/dirha_wsj5k_raw/data-fmllr-tri4/sim_dev_onlyrev /home/mravanelli/kaldi-trunk/egs/dirha_wsj5k/dirha_wsj5k_raw/exp/exp_cntk1/decode_cntk_sim_dev_onlyrev_gpu4 cntk configFile=conf/cntk_config//CNTK2_write.config DeviceNumber=0 modelName=/home/mravanelli/kaldi-trunk/egs/dirha_wsj5k/dirha_wsj5k_raw/exp/exp_cntk1/cntk.dnn.29 labelDim=3288 featDim=40 action=write ExpDir=/home/mravanelli/kaldi-trunk/egs/dirha_wsj5k/dirha_wsj5k_raw/exp/exp_cntk1`

With this setup I have the following results:

1. If I set "**DeviceNumber=-1**" (cpu) it takes a lot of time, but the performance of the system seems reasonable (WER=20.8%).
2. If I set "**DeviceNumber=0**" (gpu) the accuracy drops dramatically due to the out of memory error (WER=36.5%) . The accuracy is low just because some sentences have an empty transcription. 
3. If I set "**DeviceNumber=0**" (gpu) and I add in the config "**shareNodeValueMatrices=true**" I don't have any out of memory errors, but the accuracy is even worse (WER=66.6%). Here all the sentences have a corresponding transcription, but it is typically very poor.

Any idea?

Thank you!

**Comment by amitaga** [comment]
Please try the latest code as we recently fixed a couple of issues related to the memory sharing feature, and let us know if the problem persists. 

Also, in case the problem persists let us know the commit number that you see the issue with and also if you see the issue with both DeviceNumber=-1 and shareNodeValueMatrices=true set.

**Comment by frankseide** [comment]
(Side question: For case 2., is the output identical (or near-identical) between CPU and GPU?)

**Comment by wolfma61** [comment]
@mirco86 - did this fix your problems?

**Comment by mirco86** [comment]
The "out of memory" problem is solved, but the kaldi compilation error
remains (a pull request is pending...)

Mirco

**Comment by JJMEI** [comment]
@mravanelli 
hi mravanelli ,now i want to use kaldi's decoder ，but here always has errors
can you help me? and i want to know how do you design configFile 

here is my configFile
# Note: This sample uses the deprecated NdlNetworkBuilder.
#       An updated version using BrainScript is coming soon.
#       Please find updated samples on Github, https://github.com/Microsoft/CNTK/tree/master/Examples /...
#
command=trainNetwork
Truncated=false
precision=float
deviceId=0
stderr=$ExpDir$/log/$logFile$
traceLevel=2
 modelPath=$ExpDir$/$modelName$
# TRAINING CONFIG
trainNetwork = {

    action = "train"

    BrainScriptNetworkBuilder = {
                                    # number of distinct labels



        model = Sequential (

        ConvolutionalLayer {128, (9:9), stride = (1:1), pad = false} : ReLU :
        MaxPoolingLayer    {(4:1), stride=(4:1)} :
        ConvolutionalLayer {256, (4:3), stride = (1:1), pad = false} : ReLU :










        DenseLayer         {1024, activation=ReLU} : Dropout :
        DenseLayer         {1024, activation=ReLU} : Dropout :
        DenseLayer         {1947, activation=Softmax}

    )

    # inputs
    features = Input {(43:11:1)}
    labels = Input {1947}


        # apply model to features
        ol = model (features)

        # loss and error computation
        ce   = CrossEntropyWithSoftmax (labels, ol)
        errs = ClassificationError (labels, ol)

        # declare special nodes
        featureNodes    = (features)
        labelNodes      = (labels)
        criterionNodes  = (ce)
        evaluationNodes = (errs)
        outputNodes     = (ol)
    }

    SGD={
        epochSize=0
        minibatchSize=256
        #learningRatesPerMB=0.1:1
        learningRatesPerMB=0.0008:0.001
        momentumPerMB=0:0.009
        dropoutRate=0.0
        maxEpochs=1
        numMBsToShowResult=100


        #settings for Auto Adjust Learning Rate
        AutoAdjust={
            reduceLearnRateIfImproveLessThan=0
            loadBestModel=true
            increaseLearnRateIfImproveMoreThan=1000000000
            learnRateDecreaseFactor=0.5
            autoAdjustLR=AdjustAfterEpoch
            learnRateAdjustInterval=1
        }

        gradientClippingWithTruncation=true
        clippingThresholdPerSample=1#INF

    }
    # Parameter values for the readerstride = 1
    reader={
        # reader to use
        readerType=Kaldi2Reader
        readMethod=blockRandomize
        frameMode=true
        Truncated=false
        nbruttsineachrecurrentiter=1
        miniBatchMode=Partial
        randomize=1000000
        verbosity=0
        features={
            dim=$featDim$
            scpFile=$inputCounts$
            rx=$inputFeats$
            featureTransform=$featureTransform$
        }

        labels={
            mlfFile=$inputLabels$
            labelDim=$labelDim$
            labelMappingFile=$labelMapping$
        }
    }


    cvReader={
        # reader to use
        readerType=Kaldi2Reader
        readMethod=blockRandomize
        frameMode=true
        miniBatchMode=Partial
        randomize=Auto
        verbosity=0
        features={
            dim=$featDim$
            scpFile=$cvInputCounts$
            rx=$cvInputFeats$
            featureTransform=$featureTransform$
        }

        labels={
            mlfFile=$cvInputLabels$
            labelDim=$labelDim$
            labelMappingFile=$labelMapping$
        }
    }
}

****************************************************************

command=$action$
#numCPUThreads=$numThreads$

precision=float

write=[
    action=write
    modelPath=$modelName$
    outputNodeNames=ScaledLogLikelihood

    # deviceId=-1 for CPU, >=0 for GPU devices
    deviceId=-1
    traceLevel=1

    printValues=true

    reader=[
      # reader to use
      readerType=Kaldi2Reader
      readMethod=blockRandomize
      frameMode=false
      miniBatchMode=Partial
      randomize=Auto
      verbosity=0
      features=[
	    dim=$featDim$
	    scpFile=$inputCounts$
	    rx=$inputFeats$
      ]

    ]
    writer=[
      # reader to use
      writerType=Kaldi2Reader
      readMethod=blockRandomize
      frameMode=false
      miniBatchMode=Partial
      randomize=Auto
      verbosity=0
      ScaledLogLikelihood=[
        dim=$labelDim$
        Kaldicmd="ark:-"
	    scpFile=$inputCounts$
      ]
    ]

]
*********************************************************************************************
train_cntk2.sh
#!/bin/bash

# This is the 2nd version of CNTK recipe for AMI corpus.
# In this recipe, CNTK directly read Kaldi features and labels,
# which makes the whole pipline much simpler. Here, we only
# train the standard hybrid DNN model. To train LSTM and PAC-RNN
# models, you have to change the ndl file. -Liang (1/5/2015)

. ./path.sh
#expdir=/home/m/CNTK/Examples/Speech/BYLW   #工作目录
expdir=/home/m/CNTK_V2.0_Fianl/CNTK/Examples/Speech/BYLW/timit     #工作目录
datadir=/home/m/kaldi-master/egs/timit/s5/data-fbank   #特征数据/home/m/kald-new/egs/BYLW/s5/data-spectrogram
alidir=/home/m/kaldi-master/egs/timit/s5/exp/tri3_ali                                                    #对齐文件夹/home/m/kald-new/egs/BYLW/s5/exp/tri4b_ali

labelDim=1947  #标签维度
featDim=473   #特征维度
stage=2   #运行状态

cn_gpu=/home/m/CNTK_V2.0_Fianl/CNTK/build/release/bin/cntk    #cntk可执行文件所在目录

feats_tr="scp:$datadir/train_tr90/feats.scp"   #90%训练特征文件所在路径
feats_cv="scp:$datadir/train_cv10/feats.scp"   #10%测试特征文件所在路径
labels_tr="ark:ali-to-pdf $alidir/final.mdl \"ark:gunzip -c $alidir/ali.*.gz |\" ark:- | ali-to-post ark:- ark:- |" #训练及集标签数目
labels_cv="ark:ali-to-pdf $alidir/final.mdl \"ark:gunzip -c $alidir_cv/ali.*.gz |\" ark:- | ali-to-post ark:- ark:- |"

mkdir -p $expdir

if [ $stage -le 0 ] ; then
(feat-to-len "$feats_tr" ark,t:- > $expdir/cntk_train.counts) || exit 1;
echo "$feats_tr" > $expdir/cntk_train.feats
echo "$labels_tr" > $expdir/cntk_train.labels

(feat-to-len "$feats_cv" ark,t:- > $expdir/cntk_valid.counts) || exit 1;
echo "$feats_cv" > $expdir/cntk_valid.feats
echo "$labels_tr" > $expdir/cntk_valid.labels

for (( c=0; c<labelDim; c++)) ; do
  echo $c
done >$expdir/cntk_label.mapping

fi


if [ $stage -le 1 ] ; then

### setup the configuration files for training CNTK models ###


tee $expdir/Base.config <<EOF
ExpDir=$expdir
logFile=train_cntk_timit
modelName=cntk_timit.dnn

labelDim=${labelDim}
featDim=${featDim}
labelMapping=${expdir}/cntk_label.mapping
featureTransform=NO_FEATURE_TRANSFORM

inputCounts=${expdir}/cntk_train.counts
inputFeats=${expdir}/cntk_train.feats
inputLabels=${expdir}/cntk_train.labels

cvInputCounts=${expdir}/cntk_valid.counts
cvInputFeats=${expdir}/cntk_valid.feats
cvInputLabels=${expdir}/cntk_valid.labels
EOF

## training command ##
$cn_gpu configFile=${expdir}/Base.config configFile=/home/m/CNTK_V2.0_Fianl/CNTK/Examples/Speech/BYLW/cntk_config/CNTK_timit.cntk
#echo "$0 successfuly finished.. $dir"

fi

#解码部分的配置
if [ $stage -le 2 ] ; then

config_write=cntk_config/CNTK2_write.cntk
cnmodel=$expdir/cntk_timit.dnn

action=write
graphdir=/home/m/kaldi-master/egs/timit/s5/exp/tri3/graph
cp $alidir/final.mdl $expdir
#
#$cn_gpu configFile=$config_write DeviceNumber=0 modelName=$cnmodel labelDim=$labelDim featDim=$featDim action=$action ExpDir=$expdir
#$cn_gpu configFile=${expdir}/Base.config configFile=$config_write DeviceNumber=-1 modelName=$cnmodel labelDim=$labelDim featDim=$featDim action=$action ExpDir=$expdir
cntk_string="$cn_gpu  configFile=$config_write DeviceNumber=-1 modelName=$cnmodel labelDim=1947 featDim=43 action=$action ExpDir=$expdir"
scripts/decode_cntk2.sh  --nj 8 --cmd run.pl  --acwt 0.0833 $graphdir $datadir/test $expdir/decode "$cntk_string" || exit 1;

fi
********************************************************************************************
and the log file
# /home/m/CNTK_V2.0_Fianl/CNTK/build/release/bin/cntk configFile=cntk_config/CNTK2_write.cntk DeviceNumber=-1 modelName=/home/m/CNTK_V2.0_Fianl/CNTK/Examples/Speech/BYLW/timit/cntk_timit.dnn labelDim=1947 featDim=43 action=write ExpDir=/home/m/CNTK_V2.0_Fianl/CNTK/Examples/Speech/BYLW/timit inputCounts=/home/m/kaldi-master/egs/timit/s5/data-fbank/test/split8/1/cntk_dev.counts inputFeats=/home/m/kaldi-master/egs/timit/s5/data-fbank/test/split8/1/cntkOutput.scp | latgen-faster-mapped --min-active=200 --max-active=7000 --max-mem=50000000 --beam=13.0 --lattice-beam=8.0 --acoustic-scale=0.0833 --allow-partial=true --word-symbol-table=/home/m/kaldi-master/egs/timit/s5/exp/tri3/graph/words.txt /home/m/CNTK_V2.0_Fianl/CNTK/Examples/Speech/BYLW/timit/final.mdl /home/m/kaldi-master/egs/timit/s5/exp/tri3/graph/HCLG.fst ark:- "ark:|gzip -c > /home/m/CNTK_V2.0_Fianl/CNTK/Examples/Speech/BYLW/timit/decode/lat.1.gz" 
# Started at Thu Apr 13 19:45:33 CST 2017
#
latgen-faster-mapped --min-active=200 --max-active=7000 --max-mem=50000000 --beam=13.0 --lattice-beam=8.0 --acoustic-scale=0.0833 --allow-partial=true --word-symbol-table=/home/m/kaldi-master/egs/timit/s5/exp/tri3/graph/words.txt /home/m/CNTK_V2.0_Fianl/CNTK/Examples/Speech/BYLW/timit/final.mdl /home/m/kaldi-master/egs/timit/s5/exp/tri3/graph/HCLG.fst ark:- 'ark:|gzip -c > /home/m/CNTK_V2.0_Fianl/CNTK/Examples/Speech/BYLW/timit/decode/lat.1.gz' 
CNTK 2.0rc1+ (master e1f48f, Apr 10 2017 20:33:48) on m-P55-US3L at 2017/04/13 19:45:33

/home/m/CNTK_V2.0_Fianl/CNTK/build/release/bin/cntk  configFile=cntk_config/CNTK2_write.cntk  DeviceNumber=-1  modelName=/home/m/CNTK_V2.0_Fianl/CNTK/Examples/Speech/BYLW/timit/cntk_timit.dnn  labelDim=1947  featDim=43  action=write  ExpDir=/home/m/CNTK_V2.0_Fianl/CNTK/Examples/Speech/BYLW/timit  inputCounts=/home/m/kaldi-master/egs/timit/s5/data-fbank/test/split8/1/cntk_dev.counts  inputFeats=/home/m/kaldi-master/egs/timit/s5/data-fbank/test/split8/1/cntkOutput.scp
-------------------------------------------------------------------
Build info: 

		Built time: Apr 10 2017 20:25:21
		Last modified date: Mon Apr 10 13:09:37 2017
		Build type: release
		Build target: GPU
		With 1bit-SGD: no
		With ASGD: no
		Math lib: mkl
		CUDA_PATH: /usr/local/cuda-7.5
		CUB_PATH: /home/m/cub-1.4.1
		CUDNN_PATH: /usr/local/cudnn-5.1
		Build Branch: master
		Build SHA1: e1f48f4c145ed8b7e34d064758d449a8e7cc46b5 (modified)
		Built by Source/CNTK/buildinfo.h$$0 on m-P55-US3L
		Build Path: /home/m/CNTK_V2.0_Fianl/CNTK
		MPI distribution: Open MPI
		MPI version: 1.10.3
-------------------------------------------------------------------
-------------------------------------------------------------------
GPU info:

		Device[0]: cores = 1536; computeCapability = 5.2; type = "GeForce GTX 960"; total memory = 4092 MB; free memory = 3991 MB
-------------------------------------------------------------------

##############################################################################
#                                                                            #
# write command (write action)                                               #
#                                                                            #
##############################################################################

reading script file /home/m/kaldi-master/egs/timit/s5/data-fbank/test/split8/1/cntk_dev.counts ... 24 entries
PatchOutputNodes: No node named 'ScaledLogLikelihood'; skipping

Post-processing network...

2 roots:
	ce = CrossEntropyWithSoftmax()
	errs = ClassificationError()

Validating network. 32 nodes to process in pass 1.

Validating --> labels = InputValue() :  -> [1947 x *]
Validating --> model.arrayOfFunctions[9].arrayOfFunctions[0].W = LearnableParameter() :  -> [1947 x 1024]
Validating --> model.arrayOfFunctions[7].arrayOfFunctions[0].W = LearnableParameter() :  -> [1024 x 1024]
Validating --> model.arrayOfFunctions[5].arrayOfFunctions[0].W = LearnableParameter() :  -> [1024 x 5 x 1 x 256]
Validating --> model.arrayOfFunctions[3].W = LearnableParameter() :  -> [4 x 3 x 128 x 256]
Validating --> model.arrayOfFunctions[0].W = LearnableParameter() :  -> [9 x 9 x 1 x 128]
Validating --> features = InputValue() :  -> [43 x 11 x 1 x *]
Validating --> ol.x._.x._.x._.x.x._.c = Convolution (model.arrayOfFunctions[0].W, features) : [9 x 9 x 1 x 128], [43 x 11 x 1 x *] -> [35 x 3 x 128 x *]
Validating --> model.arrayOfFunctions[0].b = LearnableParameter() :  -> [1 x 1 x 128]
Validating --> ol.x._.x._.x._.x.x._.res.x = Plus (ol.x._.x._.x._.x.x._.c, model.arrayOfFunctions[0].b) : [35 x 3 x 128 x *], [1 x 1 x 128] -> [35 x 3 x 128 x *]
Validating --> ol.x._.x._.x._.x.x = RectifiedLinear (ol.x._.x._.x._.x.x._.res.x) : [35 x 3 x 128 x *] -> [35 x 3 x 128 x *]
Validating --> ol.x._.x._.x._.x = Pooling (ol.x._.x._.x._.x.x) : [35 x 3 x 128 x *] -> [8 x 3 x 128 x *]
Validating --> ol.x._.x._.x._.c = Convolution (model.arrayOfFunctions[3].W, ol.x._.x._.x._.x) : [4 x 3 x 128 x 256], [8 x 3 x 128 x *] -> [5 x 1 x 256 x *]
Validating --> model.arrayOfFunctions[3].b = LearnableParameter() :  -> [1 x 1 x 256]
Validating --> ol.x._.x._.x._.res.x = Plus (ol.x._.x._.x._.c, model.arrayOfFunctions[3].b) : [5 x 1 x 256 x *], [1 x 1 x 256] -> [5 x 1 x 256 x *]
Validating --> ol.x._.x._.x = RectifiedLinear (ol.x._.x._.x._.res.x) : [5 x 1 x 256 x *] -> [5 x 1 x 256 x *]
Validating --> ol.x._.x._._.PlusArgs[0] = Times (model.arrayOfFunctions[5].arrayOfFunctions[0].W, ol.x._.x._.x) : [1024 x 5 x 1 x 256], [5 x 1 x 256 x *] -> [1024 x *]
Validating --> model.arrayOfFunctions[5].arrayOfFunctions[0].b = LearnableParameter() :  -> [1024]
Validating --> ol.x._.x._._ = Plus (ol.x._.x._._.PlusArgs[0], model.arrayOfFunctions[5].arrayOfFunctions[0].b) : [1024 x *], [1024] -> [1024 x *]
Validating --> ol.x._.x._ = RectifiedLinear (ol.x._.x._._) : [1024 x *] -> [1024 x *]
Validating --> ol.x._.x = Dropout (ol.x._.x._) : [1024 x *] -> [1024 x *]
Validating --> ol.x._._.PlusArgs[0] = Times (model.arrayOfFunctions[7].arrayOfFunctions[0].W, ol.x._.x) : [1024 x 1024], [1024 x *] -> [1024 x *]
Validating --> model.arrayOfFunctions[7].arrayOfFunctions[0].b = LearnableParameter() :  -> [1024]
Validating --> ol.x._._ = Plus (ol.x._._.PlusArgs[0], model.arrayOfFunctions[7].arrayOfFunctions[0].b) : [1024 x *], [1024] -> [1024 x *]
Validating --> ol.x._ = RectifiedLinear (ol.x._._) : [1024 x *] -> [1024 x *]
Validating --> ol.x = Dropout (ol.x._) : [1024 x *] -> [1024 x *]
Validating --> ol.z.PlusArgs[0] = Times (model.arrayOfFunctions[9].arrayOfFunctions[0].W, ol.x) : [1947 x 1024], [1024 x *] -> [1947 x *]
Validating --> model.arrayOfFunctions[9].arrayOfFunctions[0].b = LearnableParameter() :  -> [1947]
Validating --> ol.z = Plus (ol.z.PlusArgs[0], model.arrayOfFunctions[9].arrayOfFunctions[0].b) : [1947 x *], [1947] -> [1947 x *]
Validating --> ol = Softmax (ol.z) : [1947 x *] -> [1947 x *]
Validating --> ce = CrossEntropyWithSoftmax (labels, ol) : [1947 x *], [1947 x *] -> [1]
Validating --> errs = ClassificationError (labels, ol) : [1947 x *], [1947 x *] -> [1]

Validating network. 20 nodes to process in pass 2.


Validating network, final pass.




Post-processing network complete.

HTKMLFWriter::Init: reading output script file /home/m/kaldi-master/egs/timit/s5/data-fbank/test/split8/1/cntk_dev.counts ... 24 entries
OutputNodeNames are not specified, using the default outputnodes.
Closed Kaldi writer
LOG (latgen-faster-mapped:main():latgen-faster-mapped.cc:163) Time taken 0.428078s: real-time factor assuming 100 frames/sec is inf
LOG (latgen-faster-mapped:main():latgen-faster-mapped.cc:166) Done 0 utterances, failed for 0
LOG (latgen-faster-mapped:main():latgen-faster-mapped.cc:168) Overall log-likelihood per frame is -nan over 0 frames.
# Accounting: time=1 threads=1
# Ended (code 1) at Thu Apr 13 19:45:34 CST 2017, elapsed time 1 seconds
