### ISSUE TITLE
cuDNN failure 8: CUDNN_STATUS_EXECUTION_FAILED when training model

### ISSUE THREAD

**Issue by GCornbake** [Microsoft/CNTK#2847]
Hi, 
     The error occurs when i'm trying to train my network and I have no idea what causes it. 
     My CNTK version is 2.3 and my GPU is GForce 970.
     I've already set the minibatchsize as 2 and it doesn't work as well.
     The Traceback is as follow:

  
![problem](https://user-images.githubusercontent.com/26302466/35038535-64cea238-fb7b-11e7-9275-2e46489436da.PNG)

**Comment by KeDengMS** [comment]
What's the version of CNTK? You may try cntk.debugging.force_deterministic(0) to use cuDNN convolution algorithm that's more conservative in memory (and slower).

**Comment by GCornbake** [comment]
The CNTK version is 2.3.

**Comment by FDecaYed** [comment]
@KeDengMS My understanding is algo 0 should always work as long as there is no fp16. And since it is the first algo we call `getworkspacesize` on, it would be useful to set err to the return value of algo0 instead of `CUDNN_STATUS_EXECUTION_FAILED` in the code.
I can help with this if there is an reproduce script.

**Comment by GCornbake** [comment]
Thank you for helping. The problem was solved and the reason was my wrong understanding about the cntk.convolution() operation.
