### ISSUE TITLE
cuDNN failure 1: CUDNN_STATUS_NOT_INITIALIZED on CNTK 2.4 GPU 

### ISSUE THREAD

**Issue by bhrnjica** [Microsoft/CNTK#2950]
I am using Python 3.5 and the latest CNTK 2.4 GPU.
Tried to run Example on Faster-RCNN described [here](https://docs.microsoft.com/en-us/cognitive-toolkit/Object-Detection-using-Faster-R-CNN): with grocery dataset. 
and got this Exception.

Traceback (most recent call last):
  File "..\DetectionDemo.py", line 59, in <module>
    eval_model = od.train_object_detector(cfg)
  File "..\utils\od_utils.py", line 21, in train_object_detector
    eval_model = train_faster_rcnn(cfg)
  File "..\FasterRCNN\FasterRCNN_train.py", line 291, in train_faster_rcnn
    eval_model = train_faster_rcnn_e2e(cfg)
  File "..\FasterRCNN\FasterRCNN_train.py", line 329, in train_faster_rcnn_e2e
    e2e_lr_per_sample_scaled, mm_schedule, cfg["CNTK"].L2_REG_WEIGHT, cfg["CNTK"].E2E_MAX_EPOCHS, cfg)
  File "..\FasterRCNN\FasterRCNN_train.py", line 571, in train_model
    trainer.train_minibatch(data)                                    # update model with it
  File "C:\local\Anaconda3\envs\tf-cntk-py35\lib\site-packages\cntk\train\trainer.py", line 181, in train_minibatch
    arguments, device)
  File "C:\local\Anaconda3\envs\tf-cntk-py35\lib\site-packages\cntk\cntk_py.py", line 2975, in train_minibatch_overload_for_minibatchdata
    return _cntk_py.Trainer_train_minibatch_overload_for_minibatchdata(self, *args)
RuntimeError: cuDNN failure 1: CUDNN_STATUS_NOT_INITIALIZED ; GPU=0 ; hostname= <> ; expr=cudnnCreate(cudnn)

[CALL STACK]
    > Microsoft::MSR::CNTK::TensorView<half>::~TensorView<half>
    - Microsoft::MSR::CNTK::TensorView<half>::~TensorView<half>
    - Microsoft::MSR::CNTK::  GetCUDNNVersion
    - Microsoft::MSR::CNTK::CudaTimer::  Stop (x2)
    - Microsoft::MSR::CNTK::ConvolutionEngine<float>::  Create
    - std::enable_shared_from_this<Microsoft::MSR::CNTK::MatrixBase>::  shared_from_this (x5)
    - CNTK::Internal::  UseSparseGradientAggregationInDataParallelSGD (x3)
    - CNTK::Function::  Forward
    - CNTK::  CreateTrainer

**Comment by KeDengMS** [comment]
I noticed that before when there is a mismatch in GPU driver/CUDA version. 2.4 release uses CUDA 9, thus requires driver version 384+. Can you check NVidia-smi to find out if there's a mismatch? You can also verify that by building/running some CUDA 9 examples.

**Comment by bhrnjica** [comment]
Hi KeDengMS,
my NVIDIA driver version is 385.78. 
Also I have no problem running the example on CNTK 2.3.

**Comment by KeDengMS** [comment]
2.3 uses CUDA 8, and 2.4 uses CUDA 9. Have you verified with both CUDA 8 and CUDA 9 sample?

**Comment by jtceleron** [comment]
I am having the same problem.
My NV driver version is 385.54.
I have installed CUDA 8.0, 9.0, 9.1.
CNTK version is 2.4. CNTK can detect my GPU, and it works fine for the GettingStarted example (https://www.cntk.ai/pythondocs/gettingstarted.html).
But if I do something more complicated (maybe include a CNN layer?), I will get this error.

**Comment by KeDengMS** [comment]
Please run ldd to check where libcudnn.so.7 path:
```
ldd `python -c "import cntk;import sys;print(sys.modules['cntk'].__path__[0] + '/libs/libCntk.Math-2.4.so')"`
```
If it's not from the package's libs path, there might be mismatch of cudnn vs. cuda. CNTK python wheels for GPU contains cudnn 7 for CUDA 9.0. If you have libcudnn installed for other CUDA versions in LD_LIBRARY_PATH it might cause problem.

**Comment by jtceleron** [comment]
Thank you for your quick reply! This is exactly the cause. Actually python is using the cudnn64_7.dll in my CUDA 9.1 folder. I deleted that dll, and now the error is gone.

@bhrnjica Not sure if you have solved the problem.. If not, you may try the same method...

**Comment by bhrnjica** [comment]
Yes That could be a fix. 
But now I have problem running python code for FasterRCNN which runs correctly on cntk 2.3,
but for cntk2.4: I have two issues:
-  !# Normalization and conv layers
    feat_norm = features - Constant([[[v]] for v in cfg["MODEL"].IMG_PAD_COLOR])
this line hangs and crashes the python, 
- once i remove that line, or change type of train to E2E, I cannot load "AlexNet_ImageNet_Caffe.model" , so python crashes at 'load_model' function.

I have experienced similar issue on my SurfacePro 3 notebook which doesn't have any GPU. The code for object detection with FasterRCNN normally works for CNTK 2.3 but on CNTK 2.4 python crashes.

**Comment by spandantiwari** [comment]
@bhrnjica I recall there was some change related to the folder where it looks for the base model. Could you please try pulling from master again to get the latest code under cntk\Examples and running it? In fact, CNTK 2.5 was released last week, and it'd great if you can try this in CNTK 2.5.

**Comment by bhrnjica** [comment]
Hi @spandantiwari 

right, after I have upgraded the CNTK to version to 2.5, everything works fine.

**Comment by spandantiwari** [comment]
Great! Thanks for letting us know.
