### ISSUE TITLE
CUBLAS failure 11: CUBLAS_STATUS_MAPPING_ERROR occuring randomly while training.

### ISSUE THREAD

**Issue by MaxCarlson** [Microsoft/CNTK#3327]
I've been getting crashes with the error below on and off, unpredictably, while training my model with the Python API. Sometimes everything will be fine training for days, other times I can't get a single epoch done before it crashes. Of the two other issues [here](https://github.com/Microsoft/CNTK/issues/2621) and [here](https://github.com/Microsoft/CNTK/issues/2598) neither solution works (running as as admin or using CNTK >= 2.5). Is this something that is fixable? Maybe someone with more experience than me with CNTK's error messages can chime in?

Error message:
```
CUBLAS failure 11: CUBLAS_STATUS_MAPPING_ERROR ; GPU=0 ; hostname=DESKTOP-DEH6B8I ; expr=cublasGetMatrix((int) numRows, (int) numCols, sizeof(ElemType), Data(), (int) GetNumRows(), dst, (int) colStride)
Traceback (most recent call last):
  File "GoNet.py", line 175, in <module>
    trainNet(args)
  File "GoNet.py", line 119, in trainNet
    trainer.train_minibatch({net.arguments[0] : X, policyVar : Y, valueVar : W})
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\lib\site-packages\cntk\train\trainer.py", line 184, in train_minibatch
    device)
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\lib\site-packages\cntk\cntk_py.py", line 3027, in train_minibatch
    return _cntk_py.Trainer_train_minibatch(self, *args)
RuntimeError: CUBLAS failure 11: CUBLAS_STATUS_MAPPING_ERROR ; GPU=0 ; hostname=DESKTOP-DEH6B8I ; expr=cublasGetMatrix((int) numRows, (int) numCols, sizeof(ElemType), Data(), (int) GetNumRows(), dst, (int) colStride)

[CALL STACK]
    > Microsoft::MSR::CNTK::CudaTimer::  Stop
    - Microsoft::MSR::CNTK::CudaTimer::  Stop
    - Microsoft::MSR::CNTK::Matrix<float>::  CopySection
    - Microsoft::MSR::CNTK::Matrix<float>::  AssignValuesOf
    - CNTK::NDArrayView::  CopyFrom
    - CNTK::NDArrayView::WritableDataBuffer<CNTK::float16>
    - CNTK::TrainingParameterSchedule<unsigned __int64>::  Transform
    - CNTK::ProgressWriter::  TotalTrainingUpdates
    - CNTK::Trainer::  TrainMinibatch (x3)
    - PyInit__cntk_py (x2)
    - PyEval_EvalFrameDefault
    - Py_CheckFunctionResult
    - PyObject_CallFunctionObjArgs
```

**Comment by KeDengMS** [comment]
Have you tried to upgrade graphics driver to the latest? Besides, you may use environment variable CUDA_LAUNCH_BLOCKING=1 to get the exact location of the failure.

**Comment by MaxCarlson** [comment]
Yes, it's been updated. I'm not familiar with environment variables, do I just need to declare it inside the python program, or does CNTK need to be built with it declared like that?

**Comment by MaxCarlson** [comment]
Awesome, I'll set that and report back when it crashes again. Is there a way to do something similar for the C++ API without building it? I have a repeated silent crash that's happening even more frequently than this one. And, like this one, seems random.

**Comment by KeDengMS** [comment]
Sometimes crashes might be related to GPU hardware itself, things like heat dissipation, power supply may be part of the randomness in crash. If possible, please try similar workload using other frameworks to rule out hardware failures.

**Comment by MaxCarlson** [comment]
I've worked with pytorch and keras/tensorflow and I don't have these crashes. I've had other crashes, but I've always been able to figure out why and how to fix through error messages.

**Comment by KeDengMS** [comment]
Were you able to get GPU running at 100% with PyTorch or keras/tensorflow? If so, it might not be hardware issue.

If the cublasGetMatrix is the real location of error, it seems only used in [GPUMatrix::CopySection](https://github.com/Microsoft/CNTK/search?q=cublasGetMatrix&unscoped_q=cublasGetMatrix). And GPUMatrix::CopySection is only used in [Source/SequenceTrainingLib/parallelforwardbackward.cpp](https://github.com/Microsoft/CNTK/search?q=CopySection&unscoped_q=CopySection). This parallel lattice forward-backward code is not commonly used and may have bugs.

**Comment by MaxCarlson** [comment]
My GPU hovers around 85-95% for all frameworks with this model. With TF I was occasionally able to get it to 100%.

You think it might not be the real location? I should have the error with the environment variable set by tomorrow. Would the parallelforwardbackward code have to do with using a non-sequential network? My network is very similar to AlphaZeros. It's just a residual tower with two heads.

**Comment by kkc0923** [comment]
Same error here. cntk-gpu 2.6.0 makes exactly same error. I can't figure out the solution of this error.

**Comment by KeDengMS** [comment]
Another thing that might worth trying: [CUDA_CACHE_DISABLE](https://devblogs.nvidia.com/cuda-pro-tip-understand-fat-binaries-jit-caching/)

**Comment by kkc0923** [comment]
@KeDengMS 
I'm trying CUDA_LAUNCH_BLOCKING=1 now. If the error occurs again, I'll try CUDA_CACHE_DISABLE. Thanks.

**Comment by kkc0923** [comment]
When I set CUDA_LAUNCH_BLOCKING=1, I got different error:

```
About to throw exception 'CUDA failure 4: unspecified launch failure ; GPU=0 ; hostname=MY-HOST-NAME ; expr=cudaEventSynchronize(done)'
CUDA failure 4: unspecified launch failure ; GPU=0 ; hostname=MY-HOST-NAME ; expr=cudaEventSynchronize(done)

[CALL STACK]
    > Microsoft::MSR::CNTK::CudaTimer::  Stop
    - Microsoft::MSR::CNTK::CudaTimer::  Stop
    - Microsoft::MSR::CNTK::GPUMatrix<float>::  SetUniformRandomMask
    - Microsoft::MSR::CNTK::Matrix<float>::  SetUniformRandomMask
    - std::enable_shared_from_this<Microsoft::MSR::CNTK::MatrixBase>::  shared_from_this (x2)
    - CNTK::Internal::  UseSparseGradientAggregationInDataParallelSGD
    - std::enable_shared_from_this<Microsoft::MSR::CNTK::MatrixBase>::  shared_from_this
    - CNTK::Internal::  UseSparseGradientAggregationInDataParallelSGD
    - CNTK::Function::  Forward
    - CNTK::  CreateTrainer
    - CNTK::Trainer::  TotalNumberOfUnitsSeen
    - CNTK::Trainer::  TrainMinibatch (x2)
    - CNTK::TrainingSession::  Train
    - PyInit__cntk_py
```

**Comment by kkc0923** [comment]
Both CUDA_LAUNCH_BLOCKING and CUDA_CACHE_DISABLE do not work for me. I think that this issue is related to GPU memory.

I found that this issue only occurs when I ran GPU-consumed software (ex, 3D games) before starting cntk training. So I tried rebooting then the issue is gone away.
