### ISSUE TITLE
cuDNN failure 7: CUDNN_STATUS_MAPPING_ERROR when attempting to load and run model in two different processes on GPU(C++).

### ISSUE THREAD

**Issue by MaxCarlson** [Microsoft/CNTK#3328]
When loading two of the same model (C++) with device set to GPU(0) (from different model files or the same) I get the following error on the second (to load) process:

```
cuDNN failure 7: CUDNN_STATUS_MAPPING_ERROR ; 
GPU=0 ; hostname=DESKTOP-DEH6B8I ; 
expr=cudnnConvolutionForward(*m_cudnn, &C::One, m_inT, ptr(in), *m_kernelT, ptr(kernel), *m_conv, m_fwdAlgo.selectedAlgo, ptr(workspace), workspace.BufferSize(), &C::Zero, m_outT, ptr(out))
```

Is this related to memory in anyway, or is it not possible to have two models from separate processes on the same GPU? I need to test two models against each other, and while they won't be running at the same time they will need to be loaded. What is this error referring to?

**Comment by MaxCarlson** [comment]
I was able to solve this by assigning the device that is going to be used earlier, and loading the model with the selected device, instead of using it's default argument.

```
namespace Net
{
	CNTK::FunctionPtr	model;
	CNTK::Variable		inputVar;
	CNTK::Variable		policyOut;
	CNTK::Variable		valueOut;
        // Initializing the device here seems to allow me to run 
        // two processes simultaneously without the above error 
        const auto& device = CNTK::DeviceDescriptor::GPUDevice(0);

void init()
{
	std::ifstream ifs(modelPath + fileName, std::ifstream::in | std::ifstream::binary);

	// Previous model load without device specified
        //model	= CNTK::Function::Load(ifs);
        // New model load with device
        model	= CNTK::Function::Load(ifs, device);
	
	inputVar	= model->Arguments()[0];
	policyOut	= model->Outputs()[NetResult::MOVES];
	valueOut	= model->Outputs()[NetResult::WIN_CHANCE];
}

NetResult inference(const GameState& state, int color)
{
	NetInput input(state, color);
        //
        // Device was originally instantiated here
        //
        //const auto& device = CNTK::DeviceDescriptor::GPUDevice(0);
	auto inputVal = CNTK::Value::CreateBatch(inputVar.Shape(), input.slices, device);
	std::unordered_map<CNTK::Variable, CNTK::ValuePtr> inputDataMap = { { inputVar, inputVal } };
        ...
}
...
}
```
