### ISSUE TITLE
CNTK not detecting GPU in python

### ISSUE THREAD

**Issue by zionsoumik** [Microsoft/CNTK#3481]
Python 3.6.3 |Anaconda, Inc.| (default, Oct 15 2017, 03:27:45) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import cntk
>>> cntk.device.all_devices()
(CPU,)
 

What is wrong. I am using NVIDIA GTX 1050. I have installed CUDA and CUDNN and Swigy

**Comment by delzac** [comment]
Did you use pip install cntk-gpu?

**Comment by zionsoumik** [comment]
yes

**Comment by delzac** [comment]
If you install tensorflow or pytorch instead, can the other frameworks detect GPU?

**Comment by Joaquim-Ferrer** [comment]
I run into the same problem. I just installed cntk-gpu and its version is 2.6.
I haven't installed neither tensorflow or pytorch with gpu support. I have the exact same output.
I have CUDA 9 properly installed.

**Comment by delzac** [comment]
Did you install msvc?

**Comment by Joaquim-Ferrer** [comment]
Yes. I had installed Visual Studio 2017 before. After that I did the script
install of the cntk_gpu. The GPU is a NVIDIA1050ti. What's the best way to
check for errors?

delzac <notifications@github.com> escreveu no dia terça, 19/02/2019 à(s)
05:45:

**Comment by delzac** [comment]
Do you have both cntk and cntk-gpu on the same environment?

**Comment by Joaquim-Ferrer** [comment]
It would be weird since I did the script install of the gpu version that
created the environment.

delzac <notifications@github.com> escreveu no dia terça, 19/02/2019 à(s)
11:26:

**Comment by delzac** [comment]
Can you check if cuda/gpu is properly working by running the examples scripts inside the cuda folder

**Comment by Joaquim-Ferrer** [comment]
Yeah I found the problem there. CUDA was not connecting to the GPU.
Installed the latest drivers from NVIDIA GeForce Experience and it worked.
Thanks!

delzac <notifications@github.com> escreveu no dia terça, 19/02/2019 à(s)
12:14:
