### ISSUE TITLE
GPU compatibility issue?

### ISSUE THREAD

**Issue by messtige** [Microsoft/CNTK#3496]
I tried transfer learning tutorial, but cuDNN failure 8 occurred.

`RuntimeError: cuDNN failure 8: CUDNN_STATUS_EXECUTION_FAILED ; GPU=0 ; hostname=DESKTOP-IROUPSV ; expr=cudnnConvolutionForward(*m_cudnn, &C::One, m_inT, ptr(in), *m_kernelT, ptr(kernel), *m_conv, m_fwdAlgo.selectedAlgo, ptr(workspace), workspace.BufferSize(), &C::Zero, m_outT, ptr(out))

[CALL STACK]
    > Microsoft::MSR::CNTK::CudaTimer::  Stop
    - Microsoft::MSR::CNTK::CudaTimer::  Stop (x2)
    - std::enable_shared_from_this<Microsoft::MSR::CNTK::MatrixBase>::  shared_from_this (x2)
    - CNTK::Internal::  UseSparseGradientAggregationInDataParallelSGD
    - std::enable_shared_from_this<Microsoft::MSR::CNTK::MatrixBase>::  shared_from_this
    - CNTK::Internal::  UseSparseGradientAggregationInDataParallelSGD
    - CNTK::Function::  Forward
    - CNTK::  CreateTrainer
    - CNTK::Trainer::  TotalNumberOfUnitsSeen
    - CNTK::Trainer::  TrainMinibatch (x2)
    - PyInit__cntk_py (x2)
    - PyCFunction_Call`

My env :
Windows 10
RTX 2080 ti
CNTK 2.6.0 - GPU (pip install)
cuda 9.0 / cudnn7

**Comment by amotupal** [comment]
I have the same issue with 2080 Ti. I am using Keras with CNTK backend.

**Comment by ssohal** [comment]
I'm getting the same error with my 2080 ti. 
 CUDA version: 9.0.0
 CUDNN version: 7.0.5

**Comment by AidanConnelly** [comment]
I'm getting this error on a rented 2080Ti

**Comment by carlonjohn** [comment]
I am getting the same error with a 2080Ti using the C# CNTK API.  I can swap out with a 1080 card and it works fine. I don't see an equivalent option in C# for trying force_deterministic.  Does anyone have a solution for this?

**Comment by JimmyDeanie** [comment]
The equivalent option in C# is:
            CNTKLib.ForceDeterministicAlgorithms();
This worked out for me, but nevertheless it seems to slow down the performance of the GPU very much.
So this is not a real solution for the situation. Is there anybody out there who fixes the problem for all the users with this popular GPU please?
