### ISSUE TITLE
bidirectional LSTM out of memory error

### ISSUE THREAD

**Issue by funguy74** [Microsoft/CNTK#705]
By changing PastValue into FutureValue, I designed BLSTM based on Issue#326. Also, set truncated=false

The following is error message log

> Starting minibatch loop.
> CUDA failure 2: out of memory ; GPU=5 ; hostname=ubuntu ; expr=cudaMalloc((void**) &deviceBufferPtr, sizeof(AllocatedElemType) * numElements)

I reduced network size from 5 layer to one with small number of neurons. However, I still see the same eror. I don't think it comes from large network size.

I also have a question. It looks like truncated should be false in order to use future value. I'm wondering then how to do back propagation through time without truncation? Is there any setting I missed?

**Comment by dongyu888** [comment]
BLSTM requires the whole sequence training since it needs to go from first to last (forward direction) and last to first (backward direction). In your case, it’s like that your sequence length is too large or the number of parallel sequences you set is too large.

**Comment by funguy74** [comment]
Thanks for your answer. I reduced "nbruttsineachrecurrentiter" from 40 to 1, which looks like changing the number of parallel sequences to be executed.  Memory error disappeared after that. However, one big problem is that it looks like execution time becomes extremely slow.

BLSTM input for my simulation is acoustic feature. Therefore, its sequence length would be based on utterance, which I cannot change.  Is there any way we can change sequence length you mentioned in CNTK configuration file?

**Comment by dongyu888** [comment]
No, you have to preprocess the data. You might want to increase the number of parallel sequences till it throws error.

**Comment by funguy74** [comment]
For doublecheck, I implemented BLSTM using BS.RNNs.RecurrentLSTMP in brain script. However, still, I can't use more than 1 for nbruttsineachrecurrentiter. My training corpus is AMI and I used utterance segmentation exactly as in CNTK AMI example.

My understanding of minibatch in CNTK is that if one sequence length is bigger than minibatch size, then it will not be segmented but use it. So, for every minibatch, there is at least one full sequence. Then, I'm not sure why bidirectional LSTM needs much more memory than LSTM unless BLSTM needs much more sequences than LSTM.

Am I right? Do I miss anything?

**Comment by dongyu888** [comment]
If it’s unidirectional, truncated BPTT would do, in that case only truncated size of the samples will be used (not whole sequence). However, for BLSTM, you have to use while sequences. Also, BLSTM has both forward and backward links. If you use the same cell size, you essentially doubled your model. What’s the largest sequence you have? What’s the memory size of your GPU? These two can give you idea on how many sequences can be fit into memory.

**Comment by funguy74** [comment]
For network size, I reduced it a half for each forward or backward direction in order to maintain same number of units. Therefore, no increase of network size

From your comment, if one whole sequence is bigger than minibatch size, it will be truncated for truncated BPTT (when truncated set to be true)? 

The following is what I get answer from issue #596 which looks not consistent to your comment.  
> Naw, there is a special rule. If a sequence is longer, we will still use it, forming a minibatch on its own

Could you clarify whether a sequence is segmented or not?

**Comment by dongyu888** [comment]
What you quoted is for full sequence instead of truncated BPTT.

**Comment by funguy74** [comment]
Discussion in #596 is based on truncated BPTT (at least I assumed it) but you mean the quote only applies for full sequence training (truncated set to be false), right?

**Comment by frankseide** [comment]
With `nbruttsineachrecurrentiter=1`, your CUDA perf will be horrible because it will not be able to utilize all GPU cores. So this is best avoided if your available memory allows it.

Which reader are you using? Going forward, the way to specify the number of parallel sequences is by setting the maximum total number of time steps, not the number of sequences. You would set `nbruttsineachrecurrentiter` to 0, and `mbSize` to the maximum number of samples. CNTK will then pack as many parallel sequences as possible, until it hits the limit given by `mbSize`. This way makes better use of your available memory. We would now need to check whether the reader you are using supports this already.

**Comment by frankseide** [comment]
>Discussion in #596 is based on truncated BPTT (at least I assumed it) but you mean the quote only applies for full sequence training (truncated set to be false), right?

Yes. In case of truncated, the memory amount is always the same, it is equal to `nbruttsineachrecurrentiter` * truncation width (which in some readers is specified under the name `mbSize`, an unfortunate misnomer).

**Comment by dongyu888** [comment]
Correct. That’s the meaning of truncated.

**Comment by funguy74** [comment]
Thanks for clarification.

I use Kaldi2reader. Basically, my script is based on "run_sdm_cntk.sh" in AMI example directory of CNTK. 

I tried nbruttsineachrecurrentiter  to be zero with minibatch size of 20 but I got following error message:
> EXCEPTION occurred:nbrUttsInEachRecurrentIter cannot be less than 1

I'm not sure what I missed.

**Comment by frankseide** [comment]
KaldiReader does not support this. :( You would have to wait until the new reader architecture supports Kaldi. I don't think we have an ETA for that. My apologies.

**Comment by funguy74** [comment]
NP, I thank you for your answers. At least, I understand what's happening in BLSTM :) I'll close this thread.
