### ISSUE TITLE
error while loading shared libraries: libcudart.so.5.5

### ISSUE THREAD

**Issue by hajix** [Microsoft/CNTK#904]
Hi
I already have installed CUDA 7.5 on my linux, and also install CNTK-1-7-1-Linux-64bit-GPU. I just want to run simple2d example to test CNTK installation but I get the following error:

> cntk: error while loading shared libraries: libcudart.so.5.5: cannot open shared object file: No such file or directory

I know that I don't have libcudart.so.5.5 cause I don't install CUDA 5.5. But I'm sure that I installed CUDA 7.5 successfully, cause I run some of its samples. So I have libcudart.so.7.5 instead.

How can I fix the error? Why does CNTK 1.7 need CUDA 5.5? I had installed CNTK 1.1 and it worked with CUDA 7.5 without any problem!!

**Comment by anwald** [comment]
Hi,
From where did you get the artifacts? Did you build them on the same machine or take them from a different machine? Would you please share the Config.make for the corresponding build, if you did the build? And, one more thing, on the cntk executable, please run:   readelf -d cntk    and please do paste the full result here.

**Comment by hajix** [comment]
I downloaded cntk binary from [here](https://github.com/Microsoft/CNTK/releases), so I don't build it by myself.
the output of `readelf -d cntk` is as follow:

> Dynamic section at offset 0x7c1ba0 contains 35 entries:
  Tag        Type                         Name/Value
 0x0000000000000001 (NEEDED)             Shared library: [libcudart.so.7.5]
 0x0000000000000001 (NEEDED)             Shared library: [libnvidia-ml.so.1]
 0x0000000000000001 (NEEDED)             Shared library: [libpthread.so.0]
 0x0000000000000001 (NEEDED)             Shared library: [libcntkmath.so]
 0x0000000000000001 (NEEDED)             Shared library: [libmpi_cxx.so.1]
 0x0000000000000001 (NEEDED)             Shared library: [libmpi.so.12]
 0x0000000000000001 (NEEDED)             Shared library: [libstdc++.so.6]
 0x0000000000000001 (NEEDED)             Shared library: [libm.so.6]
 0x0000000000000001 (NEEDED)             Shared library: [libgcc_s.so.1]
 0x0000000000000001 (NEEDED)             Shared library: [libc.so.6]
 0x0000000000000001 (NEEDED)             Shared library: [ld-linux-x86-64.so.2]
 0x000000000000001d (RUNPATH)            Library runpath: [$ORIGIN/../lib:/usr/local/cuda-7.5/lib64:/usr/local/cudnn-5.1/cuda/lib64:/usr/local/CNTKCustomMKL/2/x64/parallel:/usr/local/opencv-3.1.0/lib:/usr/local/opencv-3.1.0/release/lib:/usr/local/openmpi-1.10.3/lib]
 0x000000000000000c (INIT)               0x598b40
 0x000000000000000d (FINI)               0x8a3fdc
 0x0000000000000019 (INIT_ARRAY)         0xd91bc0
 0x000000000000001b (INIT_ARRAYSZ)       224 (bytes)
 0x000000000000001a (FINI_ARRAY)         0xd91ca0
 0x000000000000001c (FINI_ARRAYSZ)       8 (bytes)
 0x000000006ffffef5 (GNU_HASH)           0x400298
 0x0000000000000005 (STRTAB)             0x45f380
 0x0000000000000006 (SYMTAB)             0x4158c8
 0x000000000000000a (STRSZ)              1218420 (bytes)
 0x000000000000000b (SYMENT)             24 (bytes)
 0x0000000000000015 (DEBUG)              0x0
 0x0000000000000003 (PLTGOT)             0xdc2000
 0x0000000000000002 (PLTRELSZ)           20880 (bytes)
 0x0000000000000014 (PLTREL)             RELA
 0x0000000000000017 (JMPREL)             0x5939b0
 0x0000000000000007 (RELA)               0x58eeb0
 0x0000000000000008 (RELASZ)             19200 (bytes)
 0x0000000000000009 (RELAENT)            24 (bytes)
 0x000000006ffffffe (VERNEED)            0x58ed30
 0x000000006fffffff (VERNEEDNUM)         6
 0x000000006ffffff0 (VERSYM)             0x588af4
 0x0000000000000000 (NULL)               0x0

**Comment by anwald** [comment]
Hi,
I cannot find any dependencies of the recent artifacts to the libcudart.so.5.5
Most likely you have some pre-existing libraries on your machine that are being found by the runtime linker that are old and themselves depend on an older version of libcudart. Would you please attempt to purge old libraries?

Alternatively, the best way to ensure that you are running with the exact same reference configuration as we are, and without any library version ambiguities, is to use our docker container to run CNTK. If you cannot resolve your issue by deleting old libraries, please try this method instead:  https://github.com/microsoft/cntk/wiki/CNTK-Docker-Containers

Please let me know how this goes.

**Comment by hajix** [comment]
Hi

It seems you were right... there was some left over from previous cuda installation on my system.
The problem was solved by purging all nvidia and cuda drivers and reinstalling them.

thank you for helping
regards
